<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Footer</title>
    <style>
        /* Customize footer styles as needed */
        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: #05300e;
            color: #fff;
            opacity: 50%;
            text-align: center;
            padding: 5px 0;
        }
    </style>
</head>
<body>
    <footer>
        Generated by SGRMRS | {{ now()->format('Y-m-d H:i:s') }}
    </footer>
</body>
</html>